Fix exploding barrels not placing decals correctly
hackerspace-ntnu/Red-Planet-Rampage pull request #362
Opened 2023-12-03 17:34 UTC by toberge

Closes #361

2023-12-04 15:16 UTC, Fueredoriku requested changes
It seems there is a problem with the updated explodingBarrel code:
![image](https://github.com/hackerspace-ntnu/Red-Planet-Rampage/assets/54811121/7b018ed0-50b4-4ca7-a11f-fe6279f650f7)

2023-12-04 15:16 UTC, Fueredoriku commented on Assets/Scripts/Interactables/ExplodingBarrel.cs
> +        Debug.Log($"Hit at {hit.point}");
Maybe remove debug?

2023-12-04 20:11 UTC, toberge commented
The issue should be fixed now 😅

2023-12-05 23:27 UTC, Fueredoriku approved these changes
Great work!

2023-12-06 07:53 UTC, merged