Fix mouse look jitter
hackerspace-ntnu/Red-Planet-Rampage pull request #394
Opened 2023-12-31 17:40 UTC by toberge

Time.deltaTime should not be used for mouse delta since it already is a delta of pixels moved across the screen. Dampening mouse input by two orders of magnitude seems to work well for this input.

Background: I'm working on the game from a laptop where only the integrated graphics work, and with low framerate the current mouse input handling showed glaring faults, jittering painfully when I tried to aim (especially with ironsights).

2024-01-01 23:16 UTC, Fueredoriku requested changes
Could you set the lookspeed to 0.0015 instead? After some testing I found this value to feel less "sluggish"

2024-01-02 17:00 UTC, toberge commented
> Could you set the mouse lookspeed to 0.0015 instead? After some testing I found this value to feel less "sluggish", as I find the mouselook speed here a bit too slow

Done. And by the way, I think we could benefit from using separate zoomed-in look speeds for mouse and gamepad, as the current zoomed-in sensitivity seems fine on gamepad and too sensitive with a mouse (though that may be subjective ofc ofc)

2024-01-03 12:44 UTC, Fueredoriku approved these changes
>  I think we could benefit from using separate zoomed-in look speeds for mouse and gamepad, as the current zoomed-in sensitivity seems fine on gamepad and too sensitive with a mouse

I think we can throw it in as a subtask in #383, as that would be nice for players to tune themselves too for the sake of personal prefferences

2024-01-03 12:53 UTC, toberge commented
I do notice that the jitter is still present on my end, so we may need to do some actual smoothing of the inputs here later

2024-01-03 12:53 UTC, merged