Make trash uplink deterministic (enough for netcode)
hackerspace-ntnu/Red-Planet-Rampage pull request #626
Opened 2024-04-30 17:38 UTC by toberge

2024-05-02 21:07 UTC, Fueredoriku requested changes
Seems like a good solution in terms of networking! 👍

The spherecast should be an overlapshere though, because the performance dies when you use a shotgun or a similar augment that spawns multiple fallinghazards.

I also noticed that with a shotgun, shooting directly below yourself will cause every shot except the first ones that hit you to teleport high into the air before falling down? Seemed like odd behaviour, but it could probably be left in with minimal impact, so don't prioritize fixing that

While I don't think you necessarily need to implement it in this PR, deterministic randomness with a seed would be great for the randomness here. We can of course implement that later, but I don't think that syncing hitpoints alone are enough in this case. This can of course wait for a later PR

2024-05-02 21:07 UTC, Fueredoriku commented on Assets/Scripts/Hazards/FallingHazard.cs
> +        if (Physics.SphereCast(transform.position + Vector3.down, spherecastRadius, -transform.up, out RaycastHit hit, fallDistance, spherecastMask))
Since this happens every fixedupdate, I think it would be better to use overlap sphere in this case

2024-05-02 21:07 UTC, Fueredoriku commented on Assets/Scripts/Hazards/FallingHazard.cs
> +    [SerializeField] private float gravity = 9.81f;
Not const and not mars gravity? 🤔
I actually think we might need to start using other gravities than mars', as I've recently read that other games tend to use way higher constants for earth gravity in games for better game feel, but I'll slot that discussion up for next meeting I think.
I think this probably should be const tho.

2024-05-04 20:18 UTC, toberge commented on Assets/Scripts/Hazards/FallingHazard.cs
> +        if (Physics.SphereCast(transform.position + Vector3.down, spherecastRadius, -transform.up, out RaycastHit hit, fallDistance, spherecastMask))
Rewritten to use OverlapCapsule. Performance still takes a hit when launching trash, but should not be as significant as before. (didn't check the FPS counter when I tested the previous version)

2024-05-04 20:19 UTC, toberge commented on Assets/Scripts/Hazards/FallingHazard.cs
> +    [SerializeField] private float gravity = 9.81f;
Exposed it in order to tune it more easily, but that didn't turn out to be necessary as it already felt appropriate.
Made it a constant now.
Physically accurate Mars gravity is too weak for our purposes 😈

2024-05-06 00:26 UTC, Fueredoriku approved these changes
Nice!

After some testing with the profiler, I found the audio to be a suprisingly big culprit for the performance loss, specifically when it's called 11 times in quick succesion from onGround in fixedupdate with a shotgun. To further optimize, we could probably cap a maximum amount of audio that can be played from trash at the same time
![image](https://github.com/hackerspace-ntnu/Red-Planet-Rampage/assets/54811121/115a8ee8-55f7-43c8-aa3f-57107b4bf7b3)

I don't think we need to do that right now necessarily, as we could probably just put up a new issue instead. In the meantime I'll leave an approve for you to use at your discretion 🤠👍

2024-05-06 19:56 UTC, toberge commented
Since the audio issue isn't strictly related to this PR I'll merge it and add an issue for it. Seems like something we could improve in other places as well (including for the shotgun itself; it still plays 8x the same firing sound)

2024-05-06 19:56 UTC, merged