Add max chip amount
hackerspace-ntnu/Red-Planet-Rampage pull request #724
Opened 2024-06-10 22:38 UTC by Fueredoriku

- Add visual feedback for the max cap

- Add chip sprite to bidsigns for consistency

2024-06-15 17:00 UTC, toberge requested changes
Seems to work as intended, though the color choice isn't ideal. It shouldn't be pure #ff0000 >:(, try using a color that is in use elsewhere in the game. And perhaps show 20 (MAX) instead of just MAX on the chip popup.

![image](https://github.com/hackerspace-ntnu/Red-Planet-Rampage/assets/44986729/a9390f0b-1da1-4414-bc0b-fcff29dae5d0)

2024-06-15 17:01 UTC, toberge commented on Assets/Scripts/UI/PlayerHUDController.cs
> +        Debug.Log(amount);
Please remove these log statements :)))))

2024-06-19 14:46 UTC, Fueredoriku commented on Assets/Scripts/UI/PlayerHUDController.cs
> +        Debug.Log(amount);
Fixed 👍

2024-06-19 19:16 UTC, toberge approved these changes
Looks like a better choice of red 👍

2024-06-19 19:21 UTC, merged