Feature/ui3
hackerspace-ntnu/Red-Planet-Rampage pull request #919
Opened 2024-12-28 20:22 UTC by ThomasJGabrielsen

Replace Main menu UI with more modern alternative, and expand on the menu scene with new models: 
![Screenshot 2024-12-11 205221](https://github.com/user-attachments/assets/41b276ab-fee0-4d4d-8e3f-577457a48eef)

2024-12-29 15:46 UTC, toberge requested changes
Overall very nice, especially
- cool new buttons that have better transitions (could perhaps use a background in some cases but ehhh)
- nice that we also have the sliding cowbot backdrop for the descriptions
- torii gate

However, I found a few issues:

- keybind and look options still have black text
- keybinding reset button looks a little scuffed
  ![image](https://github.com/user-attachments/assets/ba1209cf-c133-443e-ac76-2928a92b766d)
- cowbot background no longer moves on the loading screen :/
- queue meny looks weird w/o steam connection, and keyboard navigation breaks when you press down from the back button:
  ![image](https://github.com/user-attachments/assets/afb91ed6-fdc3-4faa-a4e5-9b606cba7d55)
- Pressing down from Three Strikes jumps straight to the back button in local play and friends only menu:
  ![image](https://github.com/user-attachments/assets/ea0a9e2b-6a22-4610-a557-a353ba542fd1)
- In the queue menu, it doesn't even move from that button:
  ![image](https://github.com/user-attachments/assets/498cbfc7-665c-4b40-bc87-d9f6d1d70d06)
- Custom gamemode menu doesn't have the fancy new background *but* white text:
  ![image](https://github.com/user-attachments/assets/032d21b5-7597-483c-a7bb-23a435ee8262)
- Pause menu has different text size for the two buttons
- and sometimes I need to press the movement key twice to actually move from button to button, so something seems to be mildly borked there?

2024-12-29 15:46 UTC, toberge commented on Assets/Scripts/UI/MainMenu/MainMenuMoveCamera.cs
> +        //    .append(LeanTween.rotateY(mainMenuCamera.gameObject, 10, cameraSpeed).setEaseInOutQuart());
muh settings view -_-

2024-12-29 15:48 UTC, toberge commented on Assets/Scripts/UI/TilingCowboys.cs
> +    // Start is called before the first frame update
pls remove standard comments here :))))

2024-12-29 15:49 UTC, toberge commented on Assets/Scripts/UI/TilingCowboys.cs
> +    [SerializeField] private RawImage cowboys;
typo, should be cowbots >:)

2024-12-29 16:02 UTC, toberge commented on Assets/Materials/ThePit/metalTexture red.mat
This material is used for boxes and platforms in The Pit, please create a new material instead.

![image](https://github.com/user-attachments/assets/317cfacf-3f7e-48de-9a93-80685a0bfd1e)

2025-01-03 18:13 UTC, Fueredoriku commented on Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
This one can be reverted

2025-01-03 18:13 UTC, Fueredoriku commented on Assets/Textures/UI/Gradient.png
Not sure where this is used, but I think there are gradient options on most things that can apply an effect like this without having to rely on a texture

2025-01-03 22:38 UTC, toberge commented on Assets/Textures/UI/Gradient.png
This is the background texture for the new buttons I think, so not really an issue there?

2025-01-22 00:54 UTC, ThomasJGabrielsen commented on Assets/Textures/UI/Gradient.png
This was an experiment to test different ways of highlighting the menu, we determined that the lack of gradient was best, so I'm removing the file next push.

2025-01-22 01:20 UTC, ThomasJGabrielsen commented
In regards to @toberge 's issue with the buttons being white when steam is not initialized, there seems to be a check somewhere in the code that disables the button component instead of unchecking the "interactable" boolean. I'm not sure where this check is and can't seem to find it. If you could change that @Fueredoriku as you are more familiar with that code, that would be great!

2025-01-22 01:31 UTC, ThomasJGabrielsen commented on Assets/Scripts/UI/TilingCowboys.cs
> +    [SerializeField] private RawImage cowboys;
Fixed

2025-01-22 01:31 UTC, ThomasJGabrielsen commented on Assets/Scripts/UI/TilingCowboys.cs
> +    // Start is called before the first frame update
Done

2025-01-22 01:31 UTC, ThomasJGabrielsen commented on Assets/Scripts/UI/MainMenu/MainMenuMoveCamera.cs
> +        //    .append(LeanTween.rotateY(mainMenuCamera.gameObject, 10, cameraSpeed).setEaseInOutQuart());
Goodbye

2025-01-22 21:38 UTC, Fueredoriku commented
I'll take a gander! 👍

2025-01-23 18:36 UTC, toberge commented on Assets/Scripts/UI/MainMenu/MainMenuMoveCamera.cs
> +        //    .append(LeanTween.rotateY(mainMenuCamera.gameObject, 10, cameraSpeed).setEaseInOutQuart());
...I'd like the settings view to be back though

2025-01-23 18:43 UTC, toberge commented on Assets/Materials/ThePit/metalTexture red.mat
Still an issue

2025-01-23 18:44 UTC, toberge commented on Assets/Materials/ThePit/metalTexture red.mat
again, this entire file needs to be reverted

2025-01-23 18:50 UTC, toberge commented
![image](https://github.com/user-attachments/assets/2a29660d-ebcc-41e4-af3b-7261530c1a9b)

:o

2025-01-23 18:51 UTC, toberge commented on Assets/Prefabs/Gamestate/MatchManager.prefab
pause menu appears when entering match, might be related to a change here

2025-01-23 18:56 UTC, toberge commented on Assets/Scripts/UI/TilingCowbots.cs
> +        if (rotateCowbots)
Please make this the default for the loading screen at least.

2025-01-23 18:57 UTC, toberge commented on Assets/Scripts/UI/TilingCowbots.cs
> +            Vector2 angle = new Vector2(Random.Range(-1, 1), Random.Range(-1, 1));
The random.range calls here return integers since the parameters are integers. Try `Random.Range(-1f, 1f)` for proper rotation.

2025-01-23 18:59 UTC, toberge commented
overall there are a bunch of things that are fixed and a bunch of things that aren't. we could slip this in after a few more *important* fixes and make some changes afterwards

2025-01-24 17:59 UTC, Fueredoriku commented
Fixed the revert stuff + the online buttons having the wrong background color 😁👍

2025-01-24 22:06 UTC, toberge approved these changes
it good now just pls fix camera angle for queue menu

2025-01-25 01:09 UTC, Fueredoriku commented on Assets/Scripts/UI/MainMenu/MainMenuMoveCamera.cs
> +        //    .append(LeanTween.rotateY(mainMenuCamera.gameObject, 10, cameraSpeed).setEaseInOutQuart());
Fixed

2025-01-25 01:09 UTC, Fueredoriku commented on Assets/Materials/ThePit/metalTexture red.mat
Fixed

2025-01-25 01:09 UTC, Fueredoriku commented on Assets/Materials/ThePit/metalTexture red.mat
Fixed

2025-01-25 01:09 UTC, Fueredoriku commented on Assets/Prefabs/Gamestate/MatchManager.prefab
Fixed

2025-01-25 01:09 UTC, Fueredoriku commented on Assets/Scripts/UI/TilingCowbots.cs
> +        if (rotateCowbots)
Fixed

2025-01-25 01:13 UTC, Fueredoriku approved these changes
Looks really nice,
Lets gooo! 👍👍

2025-01-27 20:36 UTC, toberge commented
oh by the way please do a squash merge here (lots of the commits are like "fix problem X that appeared while working on this PR" and thus not necessary to keep)

2025-01-30 23:19 UTC, merged